
[package]
name = "ferros-userspace"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = { version = "0.13.1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
