[package]
name = "ferros-userspace"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = "0.13.1"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
log = "0.4"
env_logger = "0.9"

[build-dependencies]
aya = "0.13.1"
