[package]
name = "ferros_firewall_ebpf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
aya-bpf = { git = "https://github.com/aya-rs/aya", rev = "e0dfe73f1dc0e30f51038a1e6cdd632b1833638b" }
aya-log = { git = "https://github.com/aya-rs/aya", rev = "e0dfe73f1dc0e30f51038a1e6cdd632b1833638b", optional = true }

[build-dependencies]
aya-tool = "0.1"

[features]
default = []
