[package]
name = "ferros_firewall_ebpf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
aya-bpf = { git = "https://github.com/aya-rs/aya", branch = "main", default-features = false }
